### PR TITLE
Final code

### PR DESCRIPTION
**Pull request by imnashu**

### CODE REVIEW

**Comment by Sanchitanwar0007** [comment]
Your format.html page looks good but according to assignment there must be four lists in webpage but in your webpage there are only three lists. Fourth list is nested list so create fourth list as well.

**Comment by imnashu** [comment]
Okay will do that

**Comment by Sanchitanwar0007** [comment]
Second page name should be **image.html** instead of index.html.
And the text content of second webpage should be align in left or right of image.

**Comment by imnashu** [comment]
Got it, thanks!

**Comment by imnashu** [comment]
Hey sanchit, I have made the necessary changes,

Thank you!

**Comment by saikiransathpadi** [comment]
Layout is correct. try to format the code to look more cleaner

**Review by Sanchitanwar0007 — APPROVED** [review]

**Comment by imnashu** [comment]
Got it, thanks!

**Pull request merged**
